# Generated by Django 4.2.3 on 2023-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('pavarde', models.CharField(max_length=100)),
                ('trumpas_prisistatymas', models.TextField()),
                ('logotipas', models.ImageField(upload_to='logotipai/')),
                ('socialinis_tinklas_linkedin', models.URLField(blank=True)),
                ('socialinis_tinklas_github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Profilis',
                'verbose_name_plural': 'Profiliai',
            },
        ),
        migrations.CreateModel(
            name='Projektai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iliustracijos', models.ImageField(blank=True, upload_to='')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('aprasymas', models.TextField()),
                ('technologiju_sarasas', models.TextField()),
                ('nuoroda_i_svetaine', models.URLField(blank=True)),
                ('nuoroda_i_githuba', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
    ]
